### ISSUE TITLE
Enable setting format of x and y tick labels

### ISSUE THREAD

**Issue by tgandor** [nschloe/asciiplotlib#10]
When having X values in the millions, Gnuplot likes to switch to scientific notation.
This can be changed via `set format x '%.0f'`. But asciplotlib.plot.plot() function has no room 
to pass such a setting to Gnuplot.

I see two possible scenarios to add it: 
 *  add a `format` argument (`dict`, e.g. `{'x': '%0.f', 'y': ''} - which means x as "integers", and no numbers - just ticks, on the y axis).
 *  add a `extra` argument with arbitrary Gnuplot scripts (["set format y '%0.f'", "set format x '']).

B is more versatile, but hackish, A is a single feature, but arguably consistent with existing arguments of `label`, `xlim`, `xlabel` etc.

**Comment by nschloe** [comment]
Check out the new `extra_gnuplot_arguments` argument.
