### ISSUE TITLE
Previous package versions are missing from PyPI

### ISSUE THREAD

**Issue by nonsleepr** [nschloe/asciiplotlib#19]
Getting this while trying to rebuild my package:
```
Collecting asciiplotlib==0.1.5
  Could not find a version that satisfies the requirement asciiplotlib==0.1.5 (from versions: 0.1.8)
No matching distribution found for asciiplotlib==0.1.5
```

The only version available on PyPI is `0.1.8`: https://pypi.org/project/asciiplotlib/#history

Is there a reason to delete older package versions?

**Comment by nonsleepr** [comment]
Related: #16

**Comment by nschloe** [comment]
> Is there a reason to delete older package versions?

Not really; it was a mistake. Not much I can do about it at this point though, unfortunately.
