### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by aaronsnoswell** [nschloe/asciiplotlib#20]
When trying to run the first example in the readme,

```python
import asciiplotlib as apl
import numpy

x = numpy.linspace(0, 2 * numpy.pi, 10)
y = numpy.sin(x)

fig = apl.figure()
fig.plot(x, y, label="data", width=50, height=15)
fig.show()
```

I get the following error;

```
Traceback (most recent call last):
  File "cliplot.py", line 26, in <module>
    fig.plot(x, y, label="data", width=50, height=15)
  File "C:\Users\uqasnosw\AppData\Local\Continuum\Miniconda3\envs\python36\lib\site-packages\asciiplotlib\figure.py", line 63, in plot
    self._content.append(plot(*args, **kwargs))
  File "C:\Users\uqasnosw\AppData\Local\Continuum\Miniconda3\envs\python36\lib\site-packages\asciiplotlib\plot.py", line 24, in plot
    stderr=subprocess.PIPE,
  File "C:\Users\uqasnosw\AppData\Local\Continuum\Miniconda3\envs\python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\uqasnosw\AppData\Local\Continuum\Miniconda3\envs\python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I'm using Python 3.6 on Windows 10 64-bit.

**Comment by nschloe** [comment]
Looks like you don't have gnuplot installed.

**Comment by aaronsnoswell** [comment]
I'm an idiot - didn't see the bit in the readme saying I needed gnuplot installed. Works fine now :)

**Comment by Marikson** [comment]
I have gnuplot verison 5.4 installed, and I am using python 3.9 on Windows 10 64-bit version.

But I am still facing an error, similar above:

> Traceback (most recent call last):
>   File "c:\Users\marik\Desktop\graph.py", line 8, in <module>
>     fig.plot(x, y, label="data", width=50, height=15)
>   File "C:\Users\marik\AppData\Local\Programs\Python\Python39\lib\site-packages\termplotlib\figure.py", line 63, in plot
>     self._content.append(plot(*args, **kwargs))
>   File "C:\Users\marik\AppData\Local\Programs\Python\Python39\lib\site-packages\termplotlib\plot.py", line 18, in plot
>     p = subprocess.Popen(
>   File "C:\Users\marik\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\marik\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] The system cannot find the file specified

Do you have any idea what I am missing?

**Comment by nschloe** [comment]
termplotlib needs to find gnuplot, and it looks like it has problems doing so. Perhaps gnuplot isn't in your path?

**Comment by Marikson** [comment]
You were right! I was not precise enough, when i was installing gnuplot. Just needed to add gnuplot to PATH.

Here is the [hint](https://superuser.com/questions/1042480/execute-gnuplot-from-cmd) to scroll down to see further install options.
