### ISSUE TITLE
Suggestion: add chart, a simpler parent type of histogram

### ISSUE THREAD

**Issue by pranasziaukas** [nschloe/asciiplotlib#23]
Not an issue rather than a suggestion.

I stumbled upon this package while looking to implement some simple terminal charts. Looks like an extremely neat little tool!

However, I'd love to print a straightforward horizontal bar chart... Likely something like this
```python
# passing counts and labels
fig.chart([3, 10, 5, 2], ['Cats', 'Dogs', 'Cows', 'Mice'], orientation='horizontal')
```
and get the following
```
Cats [ 3]  ████████████
Dogs [10]  ████████████████████████████████████████
Cows [ 5]  ████████████████████
Mice [ 2]  ████████
```
This is a very nearly identical implementation compared to the current `hist()`. It just takes `counts` and `labels` directly instead of deriving them from `bin_edges`.

Is it possible to refactor/separate the chart functionality?

**Comment by nschloe** [comment]
Definitely, I'll take a look.

**Comment by nschloe** [comment]
Done.
