### ISSUE TITLE
Bug with labels if 'counts' contains any float values

### ISSUE THREAD

**Issue by AugustGarcia** [nschloe/asciiplotlib#27]
Code to replicate bug is below. Will submit patch in a minute.
```
#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Horizontal Bar Chart 

import asciiplotlib as apl
import traceback

# Bug #1 - Floating point values cause errors 
try: 
        fig = apl.figure()
        fig.barh(
                [     1.0,     12,      19],   
                ["Col 1", "Col 2", "Col 3"], 
                force_ascii=False
        )
        fig.show()    
except ValueError as e:
        print(traceback.format_exc())
# Traceback (most recent call last):
#   File "ascii_chart_debug.py", line 15, in <module>
#     force_ascii=False
#   File "/usr/local/lib/python3.5/dist-packages/asciiplotlib/figure.py", line 60, in barh
#     self._content.append(barh(*args, **kwargs))
#   File "/usr/local/lib/python3.5/dist-packages/asciiplotlib/barh.py", line 50, in barh
#     out.append(fmt.format(*data))
# ValueError: Unknown format code 'd' for object of type 'float'
```

**Comment by nschloe** [comment]
That makes sense, doesn't it? The values of `counts` are integers.

**Comment by AugustGarcia** [comment]
The values seem to be floats if the numbers passed into the function are floats, unless there's some sort of cast-as-int that happens behind the scenes that I'm missing here. The specific use case this came up during was related to plotting out percents/values from 0 to 1.

Seems like the library graphs out floats fine other than the labels, unless there's a particular reason why floats would be unsupported for barh().
```
import asciiplotlib as apl 

num_attempts    = 1000
num_success     = 642
num_fail        = 358

seconds_elapsed = 1007.12 

fig = apl.figure()
fig.barh(
        [ num_attempts/seconds_elapsed, num_success/seconds_elapsed, num_fail/seconds_elapsed],   
        [ "Total"                     , "Success"                  , "Fail"                  ], 
        force_ascii=False
)
fig.show()    

# Output (With Patch) 
"""
Total    [0.99]  ████████████████████████████████████████
Success  [0.64]  █████████████████████████▋
Fail     [0.36]  ██████████████▍
"""
```

**Comment by nschloe** [comment]
> The values seem to be floats if the numbers passed into the function are floats,

`barh` was created with integer counts in mind, i.e., you have a distribution of something and you _count_ the occurrences between two particular floats, such as the values as returned by [`bincount`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.bincount.html).

I can see why it'd be useful to admit floats here, though. I'll cook up something.
