### ISSUE TITLE
Unittests failing

### ISSUE THREAD

**Issue by benlarsendk** [nschloe/asciiplotlib#6]
Does this inly work with Python 3? :(

```
==================================== ERRORS ====================================
_____________________ ERROR collecting test/test_figure.py _____________________
ImportError while importing test module '/home/bla/Downloads/asciiplotlib/test/test_figure.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_figure.py:3: in <module>
    import asciiplotlib as apl
/usr/local/lib/python2.7/dist-packages/asciiplotlib/__init__.py:14: in <module>
    from .figure import Figure, figure
/usr/local/lib/python2.7/dist-packages/asciiplotlib/figure.py:5: in <module>
    from .table import table
/usr/local/lib/python2.7/dist-packages/asciiplotlib/table.py:3: in <module>
    from collections.abc import Sequence
E   ImportError: No module named abc
```

**Comment by nschloe** [comment]
> Does this inly work with Python 3? :(

Never tested with Python 2. And honestly, everyone who hasn't switched yet should do so soon. (Python 2's EOL is next year.) I'm open to PRs that improve Python 2 compatibility though.

**Comment by nschloe** [comment]
Closing for lack of response. Feel free to reopen if this is still an issue.

**Comment by rcox771** [comment]
just ran into this too. I have a legacy python project that uses 2.7 that I prefer to stay far away from (ssh'ing as necessary). Your library looked appealing to me for this reason alone, but hit the same issue as above.

@nschloe If you're not planning on supporting 2.7, could you update your readme to list python 3+ as a req for others?

Thanks,
-Russell

**Comment by nschloe** [comment]
Done.
