### ISSUE TITLE
Figure.table fails if stdout does not have an `encoding` attribute

### ISSUE THREAD

**Issue by alexjg** [nschloe/asciiplotlib#7]
I ran into this issue when using asciiplotlib in a celery worker where celery replaces `sys.stdout` with a proxy object called `LoggingProxy` which does not have an `encoding` attribute. This seems to be valid as far as the python documentation goes so probably asciiplotlib should check if the attribute exists? The specific line that causes problem 

asciiplotlib/table.py in _get_border_chars at line 31
```
        border_chars = None
    elif isinstance(border_style, list):
        assert len(border) == 11
        border_chars = border
    else:
        if sys.stdout.encoding in ["UTF-8", "UTF8"] and not force_ascii: # Here
            border_chars = {
                "thin": ["─", "│", "┌", "┐", "└", "┘", "├", "┤", "┬", "┴", "┼"],
                "rounded": ["─", "│", "╭", "╮", "╰", "╯", "├", "┤", "┬", "┴", "┼"],
                "thick": ["━", "┃", "┏", "┓", "┗", "┛", "┣", "┫", "┳", "┻", "╋"],
                "double": ["═", "║", "╔", "╗", "╚", "╝", "╠", "╣", "╦", "╩", "╬"],
```

**Comment by nschloe** [comment]
Fair enough. Does the `LoggingProxy` support UTF8 characters?

**Comment by nschloe** [comment]
Hm, if something replaces `sys.stdout`, shouldn't that routine also be responsible for keeping all the attributes in? Many things will go wrong if you replace such basic objects with objects that have less functionality.

**Comment by nschloe** [comment]
Well, they cannot expect that all libraries play nicely when they manipulate such basic objects. Let's see what they say at https://github.com/celery/celery/issues/5077, perhaps adding `encoding` will be easy.

**Comment by alexjg** [comment]
Sorry, I'm not sure if I'm being clear. What I mean is that the documentation for the `sys.stdout` object indicates that libraries should expect `sys.stdout` to be changed to any file-like object. What I can't figure out is whether a file-like object is expected to have an `encoding` attribute, The documentation for the `io` module suggest that only some file like objects (anything descending from `TextIOBase`) have an `encoding` attribute so it might be wise to not assume the presence of an `encoding` attribute on `sys.stdout` in `asciiplotlib`.

**Comment by nschloe** [comment]
Well, how do you decide then if to print UTF8 or ASCII characters?

**Comment by nschloe** [comment]
Convinced, fixed now. Thanks for the suggestion and the persistence!
